language: Java
notifications:
  email:
    recipients:
      - mateuszollek@gmail.com
      - matylaolga@gmail.com
      #uzupełnijcie tutaj
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: releases
  api_key: $github_token
  skip_cleanup: true
  app: text-transformer
  on:
    tags: true
