language: Java
notifications:
  email:
    recipients:
      - mateuszollek@gmail.com
      - matylaolga@gmail.com
      #uzupełnijcie tutaj
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: releases
  api_key: $github_token
  file: text-transformer.jar
  skip_cleanup: true
